apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
spec:
  selector:
    app: reddit-clone
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000        # Puerto dentro del clúster
      targetPort: 3000  # Puerto en el contenedor
